table Fact_Sales
	lineageTag: 06972525-bd9b-40e5-8b05-b7dd34de97f4

	column sale_id
		dataType: int64
		formatString: 0
		lineageTag: 7c49141f-81ea-42bc-add6-10483e72a313
		summarizeBy: sum
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c9326a5d-6b62-4667-9c9e-5abf2c0aa683
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column city
		dataType: string
		lineageTag: 48c49198-ecf4-436e-9ad1-95e21ceae220
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column store_format
		dataType: string
		lineageTag: 4aa0bbe1-17e1-43c7-b29f-41c03a913c7c
		summarizeBy: none
		sourceColumn: store_format

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 66345b80-7ea3-4c96-ba36-9aca6e989177
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: ac8c4081-fe81-4fb8-995a-4af5e4e0c1c3
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: 4d68fd01-d798-4125-bd22-220aec3b374c
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: int64
		formatString: 0
		lineageTag: dc1b0bf5-a5c2-4b33-b3df-d1a49500e544
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column sales_amount
		dataType: double
		lineageTag: bda2c467-2b77-4d20-9e72-09e7fa9975e6
		summarizeBy: sum
		sourceColumn: sales_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductKey
		dataType: string
		lineageTag: f2a85f04-eafa-45fe-b191-b36c34a4fa26
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	partition Fact_Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\DARSHINI\Downloads\brewmetrics_sales.csv"),[Delimiter=",", Columns=9, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date", type date}, {"city", type text}, {"store_format", type text}, {"category", type text}, {"item", type text}, {"quantity", Int64.Type}, {"unit_price", Int64.Type}, {"sales_amount", type number}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "ProductKey", each [category] & "-" & [item])
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

